### ISSUE TITLE
Error when uploading to AWS Glacier

### ISSUE THREAD

**Issue by hilel14** [hilel14/archie#27]
```
Dec 01, 2017 3:16:56 PM org.hilel14.archie.backup.glacier.Uploader <init>
INFO: 61,861 digests found in upload history file
Dec 01, 2017 3:16:56 PM org.hilel14.archie.backup.glacier.Uploader loadIncludePattern
INFO: Including only files with extentions (csv|doc|docx|jpeg|jpg|mov|mp3|mp4|mpg|pdf|png|ppt|pptx|tif|txt|wav|xls|xls)
Dec 01, 2017 3:16:56 PM org.hilel14.archie.backup.glacier.Uploader buildTransferManager
INFO: Building glacier transfer manager using default credentials and eu-west-1 region
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Dec 01, 2017 3:16:57 PM org.hilel14.archie.backup.glacier.Uploader mainTask
INFO: Processing files in folder /var/opt/archie/assetstore
Dec 01, 2017 3:16:57 PM org.hilel14.archie.backup.glacier.Uploader mainTask
INFO: Uploading to vault archie
Dec 01, 2017 3:16:57 PM org.hilel14.archie.backup.glacier.Uploader mainTask
INFO: Dry-run flag set to false
Dec 01, 2017 4:11:51 PM org.hilel14.archie.backup.glacier.Uploader main
SEVERE: null
java.io.IOException: Error when uploading file: /var/opt/archie/assetstore/e233c87b-47c6-46ee-9c42-1bf58e054867.jpg
	at org.hilel14.archie.backup.glacier.Uploader$UploadVisitor.visitFile(Uploader.java:158)
	at org.hilel14.archie.backup.glacier.Uploader$UploadVisitor.visitFile(Uploader.java:135)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.hilel14.archie.backup.glacier.Uploader.mainTask(Uploader.java:109)
	at org.hilel14.archie.backup.glacier.Uploader.main(Uploader.java:60)
Caused by: com.amazonaws.AmazonClientException: Unable to compute hash
	at com.amazonaws.services.glacier.TreeHashGenerator.calculateTreeHash(TreeHashGenerator.java:95)
	at com.amazonaws.services.glacier.TreeHashGenerator.calculateTreeHash(TreeHashGenerator.java:59)
	at com.amazonaws.services.glacier.transfer.ArchiveTransferManager.uploadInSinglePart(ArchiveTransferManager.java:790)
	at com.amazonaws.services.glacier.transfer.ArchiveTransferManager.upload(ArchiveTransferManager.java:333)
	at com.amazonaws.services.glacier.transfer.ArchiveTransferManager.upload(ArchiveTransferManager.java:286)
	at com.amazonaws.services.glacier.transfer.ArchiveTransferManager.upload(ArchiveTransferManager.java:248)
	at org.hilel14.archie.backup.glacier.Uploader$UploadVisitor.visitFile(Uploader.java:148)
	... 5 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.amazonaws.services.glacier.TreeHashGenerator.calculateTreeHash(TreeHashGenerator.java:143)
	at com.amazonaws.services.glacier.TreeHashGenerator.calculateTreeHash(TreeHashGenerator.java:93)
	... 11 more


```

**Comment by hilel14** [comment]
כנראה נגרם כתוצאה מקובץ ריק
